// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: proto/twopc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vote int32

const (
	Vote_VOTE_YES Vote = 0
	Vote_VOTE_NO  Vote = 1
)

// Enum value maps for Vote.
var (
	Vote_name = map[int32]string{
		0: "VOTE_YES",
		1: "VOTE_NO",
	}
	Vote_value = map[string]int32{
		"VOTE_YES": 0,
		"VOTE_NO":  1,
	}
)

func (x Vote) Enum() *Vote {
	p := new(Vote)
	*p = x
	return p
}

func (x Vote) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vote) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_twopc_proto_enumTypes[0].Descriptor()
}

func (Vote) Type() protoreflect.EnumType {
	return &file_proto_twopc_proto_enumTypes[0]
}

func (x Vote) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vote.Descriptor instead.
func (Vote) EnumDescriptor() ([]byte, []int) {
	return file_proto_twopc_proto_rawDescGZIP(), []int{0}
}

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_proto_twopc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twopc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_proto_twopc_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *PrepareRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *PrepareRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type PrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          Vote                   `protobuf:"varint,1,opt,name=vote,proto3,enum=TwoPhaseCommit.Vote" json:"vote,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_proto_twopc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twopc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_proto_twopc_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareResponse) GetVote() Vote {
	if x != nil {
		return x.Vote
	}
	return Vote_VOTE_YES
}

func (x *PrepareResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_proto_twopc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twopc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_twopc_proto_rawDescGZIP(), []int{2}
}

func (x *CommitRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_proto_twopc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twopc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_twopc_proto_rawDescGZIP(), []int{3}
}

func (x *CommitResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_proto_twopc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twopc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_proto_twopc_proto_rawDescGZIP(), []int{4}
}

func (x *AbortRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type AbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortResponse) Reset() {
	*x = AbortResponse{}
	mi := &file_proto_twopc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResponse) ProtoMessage() {}

func (x *AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twopc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResponse.ProtoReflect.Descriptor instead.
func (*AbortResponse) Descriptor() ([]byte, []int) {
	return file_proto_twopc_proto_rawDescGZIP(), []int{5}
}

func (x *AbortResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AbortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_twopc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twopc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_twopc_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_twopc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twopc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_twopc_proto_rawDescGZIP(), []int{7}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_proto_twopc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twopc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_twopc_proto_rawDescGZIP(), []int{8}
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_proto_twopc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twopc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_twopc_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_twopc_proto protoreflect.FileDescriptor

const file_proto_twopc_proto_rawDesc = "" +
	"\n" +
	"\x11proto/twopc.proto\x12\x0eTwoPhaseCommit\"\xb6\x01\n" +
	"\x0ePrepareRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12<\n" +
	"\x04data\x18\x03 \x03(\v2(.TwoPhaseCommit.PrepareRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x0fPrepareResponse\x12(\n" +
	"\x04vote\x18\x01 \x01(\x0e2\x14.TwoPhaseCommit.VoteR\x04vote\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"$\n" +
	"\rCommitRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"6\n" +
	"\x0eCommitResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"#\n" +
	"\fAbortRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"5\n" +
	"\rAbortResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x0f\n" +
	"\rGetAllRequest\"\x87\x01\n" +
	"\x0eGetAllResponse\x12<\n" +
	"\x04data\x18\x01 \x03(\v2(.TwoPhaseCommit.GetAllResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*!\n" +
	"\x04Vote\x12\f\n" +
	"\bVOTE_YES\x10\x00\x12\v\n" +
	"\aVOTE_NO\x10\x012\xf8\x02\n" +
	"\x12ParticipantService\x12J\n" +
	"\aPrepare\x12\x1e.TwoPhaseCommit.PrepareRequest\x1a\x1f.TwoPhaseCommit.PrepareResponse\x12G\n" +
	"\x06Commit\x12\x1d.TwoPhaseCommit.CommitRequest\x1a\x1e.TwoPhaseCommit.CommitResponse\x12D\n" +
	"\x05Abort\x12\x1c.TwoPhaseCommit.AbortRequest\x1a\x1d.TwoPhaseCommit.AbortResponse\x12>\n" +
	"\x03Get\x12\x1a.TwoPhaseCommit.GetRequest\x1a\x1b.TwoPhaseCommit.GetResponse\x12G\n" +
	"\x06GetAll\x12\x1d.TwoPhaseCommit.GetAllRequest\x1a\x1e.TwoPhaseCommit.GetAllResponseB\x18Z\x16Two-Phase-Commit/protob\x06proto3"

var (
	file_proto_twopc_proto_rawDescOnce sync.Once
	file_proto_twopc_proto_rawDescData []byte
)

func file_proto_twopc_proto_rawDescGZIP() []byte {
	file_proto_twopc_proto_rawDescOnce.Do(func() {
		file_proto_twopc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_twopc_proto_rawDesc), len(file_proto_twopc_proto_rawDesc)))
	})
	return file_proto_twopc_proto_rawDescData
}

var file_proto_twopc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_twopc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_twopc_proto_goTypes = []any{
	(Vote)(0),               // 0: TwoPhaseCommit.Vote
	(*PrepareRequest)(nil),  // 1: TwoPhaseCommit.PrepareRequest
	(*PrepareResponse)(nil), // 2: TwoPhaseCommit.PrepareResponse
	(*CommitRequest)(nil),   // 3: TwoPhaseCommit.CommitRequest
	(*CommitResponse)(nil),  // 4: TwoPhaseCommit.CommitResponse
	(*AbortRequest)(nil),    // 5: TwoPhaseCommit.AbortRequest
	(*AbortResponse)(nil),   // 6: TwoPhaseCommit.AbortResponse
	(*GetRequest)(nil),      // 7: TwoPhaseCommit.GetRequest
	(*GetResponse)(nil),     // 8: TwoPhaseCommit.GetResponse
	(*GetAllRequest)(nil),   // 9: TwoPhaseCommit.GetAllRequest
	(*GetAllResponse)(nil),  // 10: TwoPhaseCommit.GetAllResponse
	nil,                     // 11: TwoPhaseCommit.PrepareRequest.DataEntry
	nil,                     // 12: TwoPhaseCommit.GetAllResponse.DataEntry
}
var file_proto_twopc_proto_depIdxs = []int32{
	11, // 0: TwoPhaseCommit.PrepareRequest.data:type_name -> TwoPhaseCommit.PrepareRequest.DataEntry
	0,  // 1: TwoPhaseCommit.PrepareResponse.vote:type_name -> TwoPhaseCommit.Vote
	12, // 2: TwoPhaseCommit.GetAllResponse.data:type_name -> TwoPhaseCommit.GetAllResponse.DataEntry
	1,  // 3: TwoPhaseCommit.ParticipantService.Prepare:input_type -> TwoPhaseCommit.PrepareRequest
	3,  // 4: TwoPhaseCommit.ParticipantService.Commit:input_type -> TwoPhaseCommit.CommitRequest
	5,  // 5: TwoPhaseCommit.ParticipantService.Abort:input_type -> TwoPhaseCommit.AbortRequest
	7,  // 6: TwoPhaseCommit.ParticipantService.Get:input_type -> TwoPhaseCommit.GetRequest
	9,  // 7: TwoPhaseCommit.ParticipantService.GetAll:input_type -> TwoPhaseCommit.GetAllRequest
	2,  // 8: TwoPhaseCommit.ParticipantService.Prepare:output_type -> TwoPhaseCommit.PrepareResponse
	4,  // 9: TwoPhaseCommit.ParticipantService.Commit:output_type -> TwoPhaseCommit.CommitResponse
	6,  // 10: TwoPhaseCommit.ParticipantService.Abort:output_type -> TwoPhaseCommit.AbortResponse
	8,  // 11: TwoPhaseCommit.ParticipantService.Get:output_type -> TwoPhaseCommit.GetResponse
	10, // 12: TwoPhaseCommit.ParticipantService.GetAll:output_type -> TwoPhaseCommit.GetAllResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_twopc_proto_init() }
func file_proto_twopc_proto_init() {
	if File_proto_twopc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_twopc_proto_rawDesc), len(file_proto_twopc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_twopc_proto_goTypes,
		DependencyIndexes: file_proto_twopc_proto_depIdxs,
		EnumInfos:         file_proto_twopc_proto_enumTypes,
		MessageInfos:      file_proto_twopc_proto_msgTypes,
	}.Build()
	File_proto_twopc_proto = out.File
	file_proto_twopc_proto_goTypes = nil
	file_proto_twopc_proto_depIdxs = nil
}
